# Generated by Django 4.2.11 on 2026-03-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(max_length=100, verbose_name='Vehículo/Patente')),
                ('pin', models.CharField(help_text='PIN numérico del chofer', max_length=6, verbose_name='PIN')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas/Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('nombre_local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Local')),
                ('cuil', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CUIL/CUIT')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Programada de Envío')),
                ('hora_envio_programada', models.TimeField(blank=True, null=True, verbose_name='Hora Programada de Envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('cuenta_corriente', 'Cuenta Corriente')], default='efectivo', max_length=30, verbose_name='Método de Pago')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.chofer', verbose_name='Chofer Asignado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.cliente', verbose_name='Cliente')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Compra')),
                ('umbral_alerta', models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo de Alerta')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Unidad, Pack x6, Pack x8, Caja x24', max_length=100, verbose_name='Nombre de Presentación')),
                ('cantidad_unidades', models.PositiveIntegerField(help_text='Cuántas unidades de stock representa esta presentación', verbose_name='Cantidad de Unidades')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Compra')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='stock.producto')),
            ],
            options={
                'verbose_name': 'Presentación de Producto',
                'verbose_name_plural': 'Presentaciones de Producto',
                'unique_together': {('producto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('administrativo', 'Administrativo'), ('camiones', 'Camiones')], default='ventas', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=500)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.presentacionproducto', verbose_name='Presentación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.ventas')),
            ],
        ),
    ]
